name: Build and store snap package
on:
  push:
    branches: ['master', 'v1']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build snap package
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i && npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: snap-package
          path: dist/*.snap